baseURL: https://relm4.org/blog/
languageCode: en-us
title: "Relm4 blog"
description: Exploring new realms
author: "Aaron Erhardt"

theme: "PaperMod"

outputs:
    home:
        - HTML
        - RSS
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai

params:
    description: Exploring new realms
    ShowReadingTime: true
    ShowShareButtons: true
    ShowCodeCopyButtons: true
    defaultTheme: dark
    disableThemeToggle: true
    ShowFullTextinRSS: true

    assets:
        disableHLJS: true

    socialIcons:
        - name: "rss"
          url: "https://relm4.org/blog/index.xml"
        - name: github
          url: "https://github.com/Relm4"