baseURL: https://relm4.org/blog/
languageCode: en-us
title: Relm4 blog
description: Exploring new realms
author: "Aaron Erhardt"

theme: "PaperMod"

outputs:
    home:
        - HTML
        - RSS

params:
    description: Exploring new realms
    ShowReadingTime: true
    ShowShareButtons: true
    ShowCodeCopyButtons: true
    defaultTheme: auto
    disableThemeToggle: true
    ShowFullTextinRSS: true

    socialIcons:
        - name: "rss"
          url: "https://relm4.org/blog/index.xml"
        - name: github
          url: "https://github.com/Relm4"
